Modified Requirements
nicehash/NiceHashMiner pull request #18
Opened 2017-07-13 02:14 UTC by computeronix

Added a line for Windows 10 if you are running this you should be running the Creators Build (1703) or later as this resolves a lot of issues various miners have with GPUs on previous builds.

2017-07-13 02:17 UTC, computeronix commented
Also updated Windows 7 component to mention SP1 as if you running before SP1 you are way out of support

2017-07-13 09:03 UTC, DillonN commented
Thanks for the pull request. Could you change the wording so that Windows 7 (non SP1) is the minimum, but W10 is recommended? The idea is that this section states minimum requirements, but it would be a good idea to add in brackets after minimum Windows version that W10 will get you a better experience

2017-07-13 09:06 UTC, DillonN requested changes
Change so Windows 7 is stated for minimum and W10 is after as recommended

2017-07-13 22:19 UTC, computeronix commented
done

added this  - For GPU Mining, **paging file size** of x% of your total GPU memory

what % would you look for  (on mine I gave it over 100% of my total vram data :)  but thats overkill

2017-07-13 22:20 UTC, computeronix commented
I also added a line saying up to date patches for your OS

2017-07-14 02:47 UTC, DillonN commented
Right now NHML looks for total *free* memory (physical and page file) that's 60% the total of GPU VRAM. I will likely look into changing this though so it more accurately reflects what the miners will use since more VRAM is helpful

2017-07-15 00:31 UTC, computeronix commented
k modified

2017-07-16 03:07 UTC, DillonN commented
Awesome, looks good thanks

2017-07-16 03:07 UTC, merged