Add german translation
nicehash/NiceHashMiner pull request #2446
Opened 2021-05-19 19:08 UTC by xOzryelx

Added german translation. Didn't proofread everything again, so someone should maybe do that

2021-06-02 20:46 UTC, Domdom9999 commented
Yi

2021-06-04 19:28 UTC, bastianleicht requested changes
Sehr gut Übersetzt. Habe ein paar Änderungen mal markiert. Manche Sätze hören sich nicht gut an, aber sonst wirklich top.

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "ZUR ZEIT MINING NICHT PROFITABEL"
Du hast den `.` am Ende des Satzes vergessen.

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Auswählen, wenn du die integrierte Temperatursteuerung für AMD GPUs (außer daggerhashimoto Algorithmus) deaktivieren willst"
Du hast den `.` am Ende des Satzes vergessen.

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Auswählen, wenn die BTC Werte automatisch zu einer geeigneten Einheit skalieren sollen"
`Auswählen, wenn die BTC Werte automatisch zu einer geeigneten Einheit skaliert werden sollen.` Ist eine bessere Übersetzung.

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Auswählen, wenn du die Erkennung von {0} GPUs deaktivieren möchtest"
Du hast den `.` am Ende des Satzes vergessen.

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Auswählen, um die Konsolenausgabe in eine Datei zu schreiben"
`Auswählen, wenn die Konsolenausgabe in einen Log geschrieben werden soll.` Ist einfach besser übersetzt und hört sich nicht so abgehackt an.

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Wähle, wie geprüft wird ob der Computer im Leerlauf ist, falls du die entsprechende Option ausgewählt hast. Gesperrt wird das mining starten, sobald der Computer gesperrt ist (normalerwe
`Wähle, wie geprüft wird ob der Computer im Leerlauf ist, falls du die entsprechende Option ausgewählt hast. Session Lock wird das mining starten, sobald der Computer gesperrt ist (normalerweise wenn der Bildschirm ausgeht). Eingabe-Timeout wird das Mining starten, wenn keine Eingaben für die eingestellte Anzahl an Sekunden erfolgt ist.` Ist eine bessere Übersezung.

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Wähle in welcher Währung der Mining-Profit angezeigt wird"
Du hast den `.` am Ende des Satzes vergessen.

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Fertiggestellt"
`Fertiggestellt!`

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Kopiere Einstekkungen von (Benchmarks, Algorithmus Parameter, ...)"
`Kopiere Einstellungen von (Benchmarks, Algorithmus, Parameter, ...)`

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Nur die Einstellungen kopieren"
`Nur die tuning Einstellungen kopieren`

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Aktuelle Benchmark-Einstellungen sind bereits angewendet. Hier gibts nichts zu tun"
`Aktuelle Benchmark-Einstellungen werden bereits angewendet. Hier gibts nichts zu tun.`

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Währung:"
`Angezeigte Währung:`

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Lade Miner runter"
`Lade Miner herunter`

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Ethminer Standard Blockhöhe"
`Ethminer Standard Blockhöhe:`

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Erzwinge bestimmte CPU Miner Erweiterung"
`Erzwinge bestimmte CPU Miner Erweiterung.`

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "WICHTIG! Neue Version v{0] wurde\r\nveröffentlicht. Hier klicken zu runterladen."
`WICHTIG! Neue Version v{0] wurde\r\nveröffentlicht. Hier klicken um sie herunterzuladen.`

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Wenn aktiviert, wird {0} den von dir angegebenen API Key benutzen um dich zu benachrichtigen, falls die Rentabilität geringer ist, als die eingestellte minimale Rentabilität.\nWirf einen
Du hast den `.` am Ende des Satzes vergessen.

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Ungültige Benchmark Geschwindigkeit"
Du hast das `!` am Ende des Satzes vergessen.

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Ungültiger Worker-Name!\n\nBitte gib einen validen Worker-Namen ein (Aa-Zz, 0-9, up to 15 character long)."
`Ungültiger Worker-Name!\n\nBitte gib einen validen Worker-Namen ein (Aa-Zz, 0-9, bis zu 15 Zeichen lang)`

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "LessThreads größer als die Anzahl an verfügbaren Threads pro CPU. Ich ignoriere das mal."
`LessThreads größer als die Anzahl an verfügbaren Threads pro CPU. Einstellung wird ignoriert.`

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Miner"
Du hast den `:` am Ende des Satzes vergessen.

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Minimum Leerlauf [s]:"
`Minimaler Leerlauf [s]:`

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Nicht verfügbar"
`Nicht verfügbar (N/A)`

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "{0} läuft im Demo Modus!"
`{0} läuft im DEMO Modus!`

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Setzt DAG Lastmodus für Eth-Miner"
Du hast den `.` am Ende des Satzes vergessen.

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Für die Änderung der Einstellungen muss {0} neusterten."
`Für die Änderung der Einstellungen muss {0} neustarten.`

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Starte Mining im Leerlauf"
Starte Mining falls Leerlauf

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Dynamischer Wechsel Minimum [s]"
`Wechsle Minimalen Dynamischen  [s]`

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Es gibt fehlende Dateien von der letzten Miner initialisierung. Stell sicher, dass dein Antivirus die Anwendung nicht blockiert. {0} funtkioniert eventuell nicht ohne die fehlenden Datei
`Es gibt fehlende Dateien von der letzten Miner initialisierung. Stell sicher, dass dein Antivirus die Anwendung nicht blockiert. {0} funtkioniert eventuell nicht ohne die fehlenden Dateien. Klicke Ja um {0} neu zu initialisieren um den Fehler zu beheben.`

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Aktiviert"
`Tuning Aktiviert`

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Benutze dieses Passwort beim Start des Miners und diesem Algorithmus. falls nicht gesetzt wird das Passwort der Gruppe verwendet."
`Benutze dieses Passwort beim Start des Miners und diesem Algorithmus. Falls nicht gesetzt, wird das Passwort der Gruppe verwendet.`

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Besuch uns unter www.nicehash.com"
`Besuche uns unter www.nicehash.com`

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Wir haben Drittanbieter Mining-Software integriert, die dein Mining verschnellern und eine stabilere Erfahrung bieten sollte - das kann zu einen höheren Verdienst in einer geringeren Zei
Wir haben Drittanbieter Mining-Software integriert, die dein Mining verschnellern und eine stabilere Erfahrung bieten sollte - das kann zu einen höheren Verdienst in einer geringeren Zeit führen, selbst wenn die Entwicklergebühr abgezogen wurde. Da die Drittanbieter Software nicht OpenSource ist, kann diese nicht von uns untersucht werden. NiceHash kann für die Nutzung dieser Software nicht bürgen und übernimmt keinerlei Verantwortung für jegliche verursachte Schäden, Sicherheitsvorfälle, Daten- oder Guthabenverluste, System- oder Hardwarefehler und etwaige andere Probleme. Mit der Zustimmung zu diesem Haftungsausschluss übernimmst du die volle Verantwortung für die Nutzung der nicht OpenSource Miner so wie sie sind.

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Unzureichende Berechtigungen für die NVidia TDP Einstellungen"
`Unzureichende Berechtigungen für die NVIDIA TDP Einstellungen`

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Nvidia Power Mode Einstellungen deaktiviert wegen unzureichender Berechtigung. Wenn du dieses Feature nutzen willst, musst du als Administrator ausführen."
`Nvidea` ist nicht in Caps.

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Kann die Rentabilitäsdaten nicht beziehen"
`Rentabilitätsdaten `

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Fehlende Miner_Dateien"
Der `_` sollte durch ein Leerzeichen ersetzt werden.

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Adresse der Geldbörse"
`Wallet Adresse`

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "API Port der von dieser Gruppe verwendet wird"
Du hast den `.` am Ende des Satzes vergessen.

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "API port der von ethminer für {0} GPUs verwendet wird"
Du hast den `.` am Ende des Satzes vergessen.

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Niedrigster Port für API Verbindung"
Du hast den `:` am Ende des Satzes vergessen.

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Zusätzliche Startparameter für den Miner und diesen Algorithmus"
Du hast den `.` am Ende des Satzes vergessen.

2021-06-04 19:28 UTC, bastianleicht commented on src/NiceHashMiner/translations.json
> +      "de": "Zusätzliche Startparameter für den Miner"
Du hast den `.` am Ende des Satzes vergessen.

2021-06-07 20:11 UTC, xOzryelx commented on src/NiceHashMiner/translations.json
> +      "de": "Unzureichende Berechtigungen für die NVidia TDP Einstellungen"
Hier haben wir das selbe stehen...

2021-06-11 09:44 UTC, youtacrsbyvars approved these changes

2022-01-03 12:14 UTC, closed without merging