Bulgarian translation for NiceHash Legacy
nicehash/NiceHashMiner pull request #39
Opened 2017-07-15 10:30 UTC by drkskwlkr

This is my proposal for a Bulgarian translation of the user interface for NiceHash Legacy. I have based this translation on version 1.8 of the software and can commit to maintain it for the foreseeable future.

2017-07-16 14:31 UTC, DillonN requested changes
Please add an entry for Bg in [LanguageType.cs](https://github.com/nicehash/NiceHashMinerLegacy/blob/master/NiceHashMiner/Enums/LanguageType.cs).

Also please add a translation for `Form_Main_help` after line 34 of bg.lang

2017-07-16 19:39 UTC, drkskwlkr commented
@DillonN: Done & done sir.

2017-07-18 10:50 UTC, DillonN approved these changes

2017-07-18 10:50 UTC, DillonN commented
Thank you, looks good!

2017-07-18 10:50 UTC, merged